== Überblick - Trix und die Erweiterung
Trix ist ein Open Source WYSIWYG Texteditor vom Unternehmen Basecamp, den Machern von Ruby on Rails, und wurde von den beiden Entwicklern Sam Stephenson und Javan Makhmali der Community auf GitHub zugä̈nglich gemacht. Mithilfe dieses Editors können Nachrichten, Kommentare, Artikel, Listen und vieles mehr verfasst werden. Es besitzt ein selbst entwickeltes Document Object Model (DOM), das neben den gänglichen JavaScript Events ebenso auf selbst definierte Events hört und eingebette Anhänge unterstützt.

Im Rahmen dieser Diplomarbeit wurde eine Bibliothek zur Erweiterung des WYSIWYG Texteditors entwickelt, die es dem Benutzer ermöglicht seine eigene Toolbar mit verschiedenen Button-Gruppen und Buttons zu erstellen. Diese kann anschließend von jedem Menschen, unabhängig seiner Beeinträchtigung, problemlos bedient werden und besitzt darüberhinaus neben den bereits vorhandenen Standardfunktionalitäten einige weitere.

== Events, Observer und Delegation

=== trix-initialize
Sobald das Trix-Editor Element im DOM eingefügt wird und sein Editor-Objekt zur Benutzung bereit ist, wird das Event `trix-initialize` gefeuert. +
Beim Initialisieren der Toolbar wird auf das von Trix definierte Event `trix-initialize` gehört. Damit aber nicht die Standard Toolbar sondern die erweiterte Toolbar, die diese ersetzen soll, angezeigt wird, hört bei der Trix-Extension ebenso ein `EventListener` zu. Sobald das Event gefeuert wird, werden die
standardmäßigen Button-Gruppen und Buttons mit denen aus der eigens erstellten Toolbar ersetzt und können
mit Screenreadern und Tastaturen barrierefrei bedient werden.

=== mousedown
Das `mousedown` Event wird genau zu dem Zeitpunkt gefeuert, an dem sich der Mauszeiger auf einem Element befindet und dieses drückt. +
Damit ein Button in der Trix-Toolbar aktiv ist und sozusagen "geklickt" wird, hört dieser standardmäßig auf ein `mousedown` Event. In der Erweiterung von Trix wird dieses Event simuliert mit `EventTarget.dispatchEvent()` und somit sind die Buttons in der Toolbar auch über die Tastatur bedienbar, was vor allem bei Blinden oder bei Benutzern mit motorischen Beeinträchtigungen relevant ist.

=== keydown
Wenn eine beliebige Taste gedrückt ist, wird das `keydown` Event gefeuert und liefert einen Code, der aussagt, welche Tasten im Moment gedrückt werden. +
Um den WYSIWYG Texteditor mittels einer Tastatur bedienen zu können, wurde darauf gewartet bis das `keydown` Event gefeuert wurde. Je nachdem, welche Taste gedrückt wird, wird entweder der nächste oder der vorherige Button oder die Button-Gruppe fokussiert, geklickt oder der Cursor zur weiteren Texteingabe und Textformatierung in den Editor gesetzt.

Folgende Tasten und Tastenkombinationen gelten in der Toolbar und im Editor:

[%header,cols=2*]
|===
| Taste/Tastenkombination
| Beschreibung

| `ALT + F10`                              | Befindet sich der Cursor im Editor, dann gelangt man mit dieser Tastenkombination in die Toolbar und der erste vorkommende Button wird fokussiert.
| `→` oder `↓`                             | Der nächste bzw. rechte Button in der Toolbar wird fokussiert.
| `←` oder `↑`                             | Der vorherige bzw. linke Button in der Toolbar wird fokussiert.
| `STRG` + `→`/`↓`                         | Der erste Button der nächsten bzw. rechten Gruppe wird fokussiert.
| `STRG` + `←`/`↑`                         | Der erste Button der vorherigen bzw. linken Gruppe wird fokussiert.
| `ENTER` oder `LEERTASTE`                 | Der aktuell fokussierte Button wird geklickt.
| `ESC`                                 | Befindet sich der Fokus in der Toolbar und wird die Taste gedrückt, so wird wieder der Editor fokussiert und der Cursor befindet sich an der zuletzt verwendeten Position.
| `POS1`                                   | Der erste in der Toolbar vorkommende Button wird fokussiert.
| `ENDE`                                   | Der letzte in der Toolbar vorkommende Button wird fokussiert.
|===

=== focusout
Sobald ein Element im Begriff dabei ist den Fokus zu verlieren, wird das `focusout` Event gefeuert. +
Das Dropdown Menü jedes `DropdownButtons` erhält beim Initialisieren das Attribut `hidden`, damit es zu Beginn für den Benutzer nicht sichtbar ist. Sobald der Button geklickt wird, wird auch das Menü sichtbar und der Fokus auf den ersten Button gelegt. Wenn das Menü allerdings nicht mehr fokussiert ist, reagiert der `EventListener` auf das Event `focusout` und das Dropdown Menü erhält erneut das Attribut `hidden` und wird versteckt.

== MutationsObserver
Der `MutationObserver` ist ein Interface, der Veränderungen in der Baumstruktur des DOMs beobachtet und wurde konzipiert, um die Mutation Events aus der DOM3 Events Spezifikation abzulösen. +
Sobald die Toolbar geladen wird bzw. bestimmte Buttons geklickt werden, werden einige andere Buttons deaktiviert und erhalten das Attribut `disabled`. Dieses verhindert allerdings das Fokussieren eines Buttons, was mit dem Attribut `aria-disabled` problemlos funktioniert. Abhilfe verschafft deshalb ein `MutationObserver`. Erhält ein Button nun das Attribut `disabled`, beobachtet der `MutationObserver` diese Veränderung und entfernt es. Stattdessen fügt es das Attribut `aria-disabled` hinzu und setzt es auf `true`. Bei allen anderen Buttons, die nicht deaktiviert sind, ist `aria-disabled=false`.

== Dialog Delegation
Die Delegation findet in der objektorientierten Programmierung verschieden Verwendung zur dynamischen Bindung von Methoden zur Programmlaufzeit. +
Jedem `AttributeButton` kann die Identifikation eines HTML-Elements mitgegeben werden, das einen Dialog repräsentiert und bereits im HTML-Code erstellt wurde. Die Delegation ermöglicht eine Kommunikation zwischen der Trix-Toolbar und dem Dialog. Sie dient ausschließlich dazu den Dialog zu öffnen und zu schließen, wobei zwei zusätzliche Funktionalitäten das Erstellen und das Entfernen von Links sind. Alles, was während oder nach dem Dialog geschieht, wird vom Entwickler selbst bestimmt.